@startuml ProjetGo

enum StatutAdhesion {
  ACTIF
  TERMINE
  ATTENTE_COTISATION
  GELE
}

enum StatutProjet {
  PROPOSE
  SOUMIS
  APPROUVE
  ACTIF
  TERMINE
  GELE
}

enum EtatAvancement {
  VERT
  JAUNE
  ROUGE
}

enum Frequence{
    Quotidienne
    Hebdomadaire
    Bihebdomadaire
    Mensuelle
}

class User {
  string nom
  string prenom
  string email
  string phone
  string adresse
  date Inscription
}

class Member {
  User User
  date adhesion
  StatutAdhesion statutAdhesion
}

class Participant {
  Project projet
  User User
  bool comite
}

class Responsable {}

class Comité{
}

class Project {
  string code
  string titre
  string description
  Sommaire sommaire du projet
  StatutProjet statutProjet 
  date débutEstimée
  date finEstimé
  decimal budget
  decimal totalFondsCollectés
  decimal totalDépenses
  date débutRéelle
  date finRéelle 
  EtatAvancement étatProjet
  FrequenceCompteRendu: Frequence
}

class Sommaire {
 Project projet
 string but
 string objectifs
 string bénéfices
 string risques
}

class Report {
  Project projet
  date dateReport
  string update
  string completed
  string reported
  string etatRisque
}

class Fundraising {
  Project projet
  date debut
  date fin
  decimal objective
}

class Don {
  Fundraising fundraising
  date dateDon
  decimal montant
  string typePaiement
  string nom
  string prenom
  string email
  string telephone
  string adresse
}

Member -up-|> User
Responsable -up-|> Member
Participant -up-|> User

Member "2..*" -right- "0..*" Comité: Fait partie de >
Member "1" -- Sommaire:Propose >
Comité "1" -- "1" Sommaire: Appuie >
note left of Sommaire
 Proposition de
 création de projet.
end note

Fundraising "0..*" --* "1" Project
User -- "*" Fundraising
(User, Fundraising) . Don

Responsable -- Project:Produit regulierement >
(Responsable, Project) . Report

Participant -- Project: Contribue >

@enduml