@startuml ProjetGO
enum EtatAvancement{
    Vert
    Jaune
    Rouge
}
enum StatutAdhesion{
    Actif
    Terminé
    AtteinteCotisation
    Gelé
}

enum StatutProjet{
    Proposé
    Soumis
    Approuvé
    Actif
    Terminé
    Gelé
}



class Visiteur 
class Comité

class Membre{
     +StatutAdhesion statutAdhesion
     -payerCotisation()
     -coopterProject()
}
class Donateur{
    -nom: String 
    -prenom: String 
    -email: String 
    -telephone:String 
    -adresse: String 
}


class CampagneLeveFond{

}



class Project{
    +codeProjet : String
    +titre: String
    +description: String
    +sommaire: String
    -statutProjet: StatutProjet 
    +dateDebut: Date
    +dateFin: Date
    -budget: double
    -fondsCollectes: double
    -totalDepenses: double
    +dateDebutReelle: Date
    +dateFinReelle: Date
    +etatAvancement: EtatAvancement
    +responsable: Membre
    -FrequenceCompteRendu: Frequence
    
}

enum Frequence{
    Quotidienne
    Hebdomadaire
    Bihebdomadaire
    Mensuelle
}


class Don{
    -dateDon: Date
    -montant: double
    -typePaiement: String
    -donateur: Donateur
    -campagne: CampagneLeveFond
}

class Benevole{
    -nom: String
    -prenom: String
    -email: String
    -telephone: String
    -adresse: String
    -dateAdhesion: Date
    -inscription()
}

class CompteRendu{
    -dateCompteRendu: Date
    -informationsProjet: String
    -realisationsCompletées: String
    -realisationsReportées: String
    -etatRisques: String
}
class Conseil{
    -approuverProjets()
}
class Comité{
    -soutenirProjets()
}

Membre <|-- Responsable
Membre <|-- Comité
Responsable --> CompteRendu

CompteRendu --> Comité
CompteRendu --> Conseil



Visiteur <|-- Benevole
Benevole <|-- Membre
Visiteur <|-- Donateur



Membre --> Project
Benevole --> Project
Donateur --> Don

CampagneLeveFond <-- Don
CampagneLeveFond --> Project

@enduml