@startuml Collecte
  PublicUser__Frontend -> Service__Backend: New donation request
  Service__Backend -> Payment__API: Payment Request
  Payment__API -> Service__Backend: Payment Response
  Service__Backend -> PublicUser__Frontend: Show payment form
  PublicUser__Frontend -> Service__Backend: Provide billing informations
  Service__Backend -> Payment__API: Send payment informations
  Payment__API -> Bank: Payment processing request
  Bank -> Payment__API: Payment processing response
  Payment__API -> Service__Backend: Return payment result
  Service__Backend -> Database: Register new donation request
  Database -> Service__Backend: Register new donation response
  Service__Backend -> PublicUser__Frontend: Show Payment result
@enduml

@startuml Status_Notification
  Responsable__Frontend -> Service__Backend: Show project information
  Service__Backend -> Database: Project informations request
  
  Database -> Service__Backend: Project informations response

  loop missing project status == true
    Service__Backend -> Responsable__Frontend: Show status request
    Responsable__Frontend -> Service__Backend: Set project status
  end

  Service__Backend -> Responsable__Frontend: Show project response

@enduml