@startuml Collecte
  PublicUser -> ProjetGo: New donation request
  ProjetGo -> API: Paiment Request
  API -> PublicUser: Show payment form
  PublicUser -> API: Provide billing informations
  API -> Bank: Paiment processing request
  Bank -> API: Paiement processing response
  API -> PublicUser: Show result
  API -> ProjetGo: Return result
  ProjetGo -> Database: Email notification request
  Database -> ProjetGo: Email notification response
  ProjetGo -> PublicUser: Show Thank you page  
@enduml