@startuml ProjetGo
left to right direction
:Responsable:
:Membre:
:Benevole:
:Visiteur:
:{Abstract} PublicUsr: as public

Membre -|> public
Benevole -|> public
Visiteur -|> public
Responsable -|> Membre

database "Database" as Db
database "Paiement Payment__API" as Payment__API

rectangle ProjetGo {
  Visiteur --> (Inscription)
  Benevole --> (Subscription)
  Inscription .> (Subscription) : extends

  (Paiment Subscription) as SubFee
  Membre --> SubFee
  Payment__API --> SubFee
  
  Membre --> (Creation Projet)

  Responsable --> (Gestion Projet)

  (Afficher une liste des projets) as ListeProjet
  public --> ListeProjet

  (Afficher details public d'un projet) as AccesPublic
  public --> AccesPublic
  
  (Afficher details restreint d'un projet) as AccesRestreint
  Membre --> AccesRestreint

  (Notification statut manquant) as Notify
  Db --> Notify

  (Faire un don) as Don
  public --> Don
  Payment__API --> Don

}
@enduml

@startuml GestionProjet
left to right direction

:Responsable:

rectangle GestionProjet {
  Responsable --> (Modifier le statut de projet)
  
  (Ajouter membre au projet) as AddMember
  Responsable --> AddMember

  (Ajouter benevole au projet) as AddBenevole
  Responsable --> AddBenevole

  (Afficher liste membres d'un projet) as ListeMembre
  Responsable --> ListeMembre

  (Afficher liste benevole d'un projet) as ListBenevole
  Responsable --> ListBenevole

  (Creation d'une levee de fonds) as LeveeFonds
  Responsable --> LeveeFonds
}
@enduml